import type {
  Therapist,
  DashboardStats,
  Patient,
  Appointment,
  Transaction,
  EarningsSummary,
  AppNotification,
} from "@/types";

export const mockTherapist: Therapist = {
  id: "therapist-1",
  name: "Dr. Himanshu",
  phone: "+919876543210",
  email: "himanshu@physiobuddies.in",
  specialization: "MPT Orthopedics",
  qualifications: "MPT (Ortho), BPT",
  experienceYears: 8,
  rating: 4.8,
  isOnline: true,
  isVerified: true,
  clinicName: "Physiobuddies Clinic",
};

export const mockDashboardStats: DashboardStats = {
  todaySessions: 3,
  earnedToday: 4850,
  rating: 4.8,
  weeklyEarnings: 28400,
  weeklyChangePercent: 12,
  weeklyChart: [
    { day: "Mon", amount: 2800, isToday: false },
    { day: "Tue", amount: 4100, isToday: false },
    { day: "Wed", amount: 3600, isToday: false },
    { day: "Thu", amount: 4900, isToday: true },
    { day: "Fri", amount: 3200, isToday: false },
    { day: "Sat", amount: 2100, isToday: false },
    { day: "Sun", amount: 1800, isToday: false },
  ],
  pendingTasks: 3,
};

export const mockPatients: Patient[] = [
  {
    id: "p-amit",
    name: "Amit Verma",
    age: 42,
    gender: "male",
    phone: "+919812345678",
    condition: "Lower back pain rehab",
    address: "Flat 804, Sea View Residency, Turner Rd, Bandra West, Mumbai — 400050",
    totalSessions: 14,
    lastVisit: "28 May 2026",
    tags: ["Home visit", "L4-L5", "Chronic"],
  },
  {
    id: "p-neha",
    name: "Neha Sharma",
    age: 35,
    gender: "female",
    phone: "+919812345679",
    condition: "Post-surgery knee rehab",
    totalSessions: 8,
    lastVisit: "1 Jun 2026",
    tags: ["Clinic", "Post-op", "Knee"],
  },
  {
    id: "p-rohan",
    name: "Rohan Mehta",
    age: 28,
    gender: "male",
    phone: "+919812345680",
    condition: "Shoulder impingement",
    totalSessions: 5,
    lastVisit: "3 Jun 2026",
    tags: ["Online", "Shoulder"],
  },
  {
    id: "p-priya",
    name: "Priya Nair",
    age: 52,
    gender: "female",
    phone: "+919812345681",
    condition: "Cervical spondylosis",
    totalSessions: 11,
    lastVisit: "30 May 2026",
    tags: ["Home visit", "Neck", "Chronic"],
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "appt-1",
    patientId: "p-amit",
    patientName: "Amit Verma",
    patientAge: 42,
    patientGender: "male",
    patientPhone: "+919812345678",
    time: "10:30",
    timeLabel: "10:30",
    meridiem: "AM",
    type: "home",
    status: "confirmed",
    paymentStatus: "paid",
    amount: 1200,
    condition: "Lower back pain rehab",
    address: "Flat 804, Sea View Residency, Turner Rd, Bandra West, Mumbai — 400050",
    latitude: 19.0596,
    longitude: 72.8295,
    distanceKm: 5.2,
    etaMin: 18,
    notes:
      "Chief complaint: Chronic lower back pain for 6 months, worsens after prolonged sitting. Previous MRI shows L4-L5 disc bulge. Patient prefers morning sessions. Carry resistance band. Allergic to latex gloves.",
    insurance: "HDFC Health – Verified",
    workflowStep: 2,
  },
  {
    id: "appt-2",
    patientId: "p-neha",
    patientName: "Neha Sharma",
    patientAge: 35,
    patientGender: "female",
    patientPhone: "+919812345679",
    time: "12:00",
    timeLabel: "12:00",
    meridiem: "PM",
    type: "clinic",
    status: "confirmed",
    paymentStatus: "paid",
    amount: 800,
    condition: "Post-surgery knee rehab",
    address: "Physiobuddies Clinic, Andheri West",
    latitude: 19.1364,
    longitude: 72.8296,
    distanceKm: 3.1,
    etaMin: 12,
    notes: "6 weeks post ACL reconstruction. Progressing well. Focus on proprioception.",
    workflowStep: 1,
  },
  {
    id: "appt-3",
    patientId: "p-rohan",
    patientName: "Rohan Mehta",
    patientAge: 28,
    patientGender: "male",
    patientPhone: "+919812345680",
    time: "04:00",
    timeLabel: "04:00",
    meridiem: "PM",
    type: "online",
    status: "confirmed",
    paymentStatus: "pending",
    amount: 600,
    condition: "Shoulder impingement",
    notes: "Online consultation. Review exercise progress.",
    workflowStep: 1,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    patientName: "Amit Verma",
    amount: 1200,
    type: "session",
    status: "paid",
    date: "2026-06-17",
    dateLabel: "Today",
    sessionType: "home",
  },
  {
    id: "tx-2",
    patientName: "Neha Sharma",
    amount: 800,
    type: "session",
    status: "paid",
    date: "2026-06-17",
    dateLabel: "Today",
    sessionType: "clinic",
  },
  {
    id: "tx-3",
    patientName: "Priya Nair",
    amount: 1500,
    type: "session",
    status: "pending",
    date: "2026-06-16",
    dateLabel: "Yesterday",
    sessionType: "home",
  },
  {
    id: "tx-4",
    patientName: "Weekly bonus",
    amount: 2400,
    type: "bonus",
    status: "paid",
    date: "2026-06-15",
    dateLabel: "15 Jun",
  },
  {
    id: "tx-5",
    patientName: "Bank payout",
    amount: 22000,
    type: "payout",
    status: "paid",
    date: "2026-06-09",
    dateLabel: "9 Jun",
  },
];

export const mockEarnings: EarningsSummary = {
  totalThisWeek: 28400,
  changePercent: 12,
  totalThisMonth: 98600,
  pendingPayout: 6300,
  nextPayoutDate: "Mon, 22 Jun 2026",
  weeklyChart: mockDashboardStats.weeklyChart,
};

export const mockNotifications: AppNotification[] = [
  {
    id: "n-1",
    type: "appointment",
    title: "New appointment confirmed",
    body: "Amit Verma — Home visit today at 10:30 AM",
    timestamp: "9:15 AM",
    read: false,
    actionUrl: "/appointment/appt-1",
  },
  {
    id: "n-2",
    type: "payment",
    title: "Payment received",
    body: "Rs 1,200 from Amit Verma has been credited",
    timestamp: "8:42 AM",
    read: false,
  },
  {
    id: "n-3",
    type: "task",
    title: "Treatment note pending",
    body: "Complete Neha's treatment note before 6 PM payout review",
    timestamp: "Yesterday",
    read: true,
    actionUrl: "/treatment",
  },
  {
    id: "n-4",
    type: "system",
    title: "Document re-upload required",
    body: "Your registration certificate was rejected. Please re-upload a clear scan.",
    timestamp: "2 days ago",
    read: true,
  },
];
